exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss", "reference.txt", "samplePage.md"]
title: "Roselle Auto Services Inc"         # shown in large text
description: "Site" # shown under the title
tagline: "Body Shop Linden NJ"     # shown in title bar beside the title
version: "0.1.2"              # "Currently v1.2.3"
url:     "http://roselleautoservices.github.io"    # Used by the Atom feed
baseurl: ""                   # URL of site relative to domain
parse_block_html: true
markdown: redcarpet
permalink: /writing/:title

mapping:
    provider: google_js
    api_key: AIzaSyCHoXq9HOn0XgxOK6rCNOVOg99RN5_20lY
    zoom: 10
    dimensions:
        width: 600
        height: 400