# config.yml

backend:
  name: github
  repo: roselleautoservices/roselleautoservices.github.io
  branch: main # Branch to update (optional; defaults to master)
  base_url: https:"https://roselleautoservices.com
media_folder: 'assets/uploads'
collections:
- name: 'pages'
  label: 'Pages'
  editor:
    preview: true
  files:
    - label: 'About Page'
      name: 'about'
      file: 'about/index.md'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
        - { label: 'Body', name: 'body', widget: 'markdown' }